### ISSUE TITLE
py version?

### ISSUE THREAD

**Issue by lutsifer** [sebastianst/GenesisZ#11]
I am trying to install this on ethos so i can use my gpus.
Installation went perfect! However making it work - not so good  :)

I am having hard times to find the proper py version to start it.
with < 3.5 it gives me async syntax problems:

```
File "./genesis.py", line 166
    async def findValidSolution(eh, solverCmd):
            ^
SyntaxError: invalid syntax
```

And with 3.5 bitcoin lib is missing:
```
Traceback (most recent call last):
  File "./genesis.py", line 18, in <module>
    from bitcoin.core import *
ImportError: No module named 'bitcoin.core'
```

Any help would be appreciated.

**Comment by sebastianst** [comment]
This package indeed requires python 3.5 because of the async stuff.
Regarding `bitcoin`, as usual and mentioned in the README, all required modules need to be installed with `pip install -r requirements.txt`.
