### ISSUE TITLE
ImportError: No module named 'zcash.core'

### ISSUE THREAD

**Issue by miranos** [sebastianst/GenesisZ#12]
How to solve this error please ?

**Comment by sebastianst** [comment]
Follow the instructions in the README, especially `git clone --recursive` to also checkout the `zcash` submodule.

**Comment by miranos** [comment]
Thank you for your answer.

After solving the problem and installed silentarmy, i noticied that silentarmy  could work only on NVIDIA etc.. what about CPU ? i need to mine only the genesis block for altcoin, is it possible ?

Any CPU solution with your script pls ?

**Comment by sebastianst** [comment]
Silentarmy uses OpenCL, which works on Nvidia, AMD and Intel CPUs. So you should be able to compile it on your PC, given that you have the right OpenCL libs installed, see silentarmy's README.
Over the last days I have implemented Tromp's Equihash solver, which uses the CPU. With it we can also finally mine regtest solutions. I'll push the update tonight probably! Stay tuned.

**Comment by miranos** [comment]
I am unable to get silentarmy working on my intel cpu.

Always getting this error:

Solving default all-zero 140-byte header
```
Building program
ASSERTION FAILED: insn2.header.opcode == GEN_OPCODE_NOP
  at file /build/beignet-5qGeBM/beignet-1.1.1/backend/src/backend/gen_encoder.cpp, function virtual void gbe::GenEncoder::patchJMPI(uint32_t, int32_t, int32_t), line 1043
Trace/breakpoint trap (core dumped)
```

Hope your new update will work on my PC, waiting for it impatiently, i will be here checking the new update since really need it, hope it will be updated tonight !

Thank you sir !

**Comment by sebastianst** [comment]
This is obviously a silentarmy issue, please post on their bug tracker.
The update will come tonight ;)

**Comment by miranos** [comment]
Issue posted in their bug tracker.

Waiting for your solution tonight sir, i think it will be better than using silentarmy and come with more features espacially with regtest genesis generation.

By the way, thank you for your efforts and your awesome work.

**Comment by sebastianst** [comment]
Thanks! If you like it, give this project a ⭐ ;)

**Comment by miranos** [comment]
Done !

**Comment by sebastianst** [comment]
Tromp now supported, see end of #7 and README. I haven't tested regtest mining yet though.

**Comment by miranos** [comment]
I will test it now, i was waiting for you.

I will give feedback asap

Thank you

**Comment by miranos** [comment]
I am trying to generate mainnet, but there something wrong ! up to 5 hours turning without founding the genesis, here the command:

`./genesis.py -c mainnet -t 1525713114 -z Testfor41b3ad374fe454b5535b8189a6c977176c6640aa2b694b0d16aa852c758a4ad10 -p 04e
edebd8f7ddc56038cfff5a8049bfba8a927de78819c8f018b2e7d434f0cbad9c2450eb1d4ef036628ed0cf164647f8abd4bfa3f61abec6b852711b22abc1bcf7 -s "/home/developer/equihash/equi" -S tromp -b 0x1f07fff -v -n ddaa -T 4 -r 100000`

Note that from `0` to `ddaa` nothing found aswell !

Actual nonce is:
`0000000000000000000000000000000000000000000000000000000000013f82`

--
Now
--
`00000000000000000000000000000000000000000000000000000000000156a2`


And not yet found !

When i don't use` -b 0x1f07fff `he find it fast, but i think it's required, what the default bite you are checking on please ?

DO i have to continue or stop here to check if something is wrong ?

Many thank's sir in advance.

Notice that regtest is generated in no time !

**Comment by sebastianst** [comment]
See `genesis.py`, the default `nBits` value is `0x1f07ffff`. So no need to explicitly set `-b 0x1f07ffff`. You made a mistake and forgot the last `f`, which is why you set a much higher difficulty and it will probably take very long to find a solution! Better just omit `-b` or set it to the right value `0x1f07ffff`, note the four `f` at the end.

I actually just ran my sa-solver with your command, but used `-Z` instead of `-z` because it seems you wanted to specify your `pszTimestamp` directly. I find a solution for nonce `0x00...002367` with
```
./genesis.py -c mainnet -t 1525713114 -Z Testfor41b3ad374fe454b5535b8189a6c977176c6640aa2b694b0d16aa852c758a4ad10 -p 04edebd8f71c56038cfa665a8049bfba8a927de78819c8f018b2e7d434f0cbad9c2450eb1d4ef036628e60cf164647f8abd4bfa3f61abec6b852711b22abc1bcf7 -s ../silentarmy/sa-solver -r 100000
```
You can confirm it by setting `-n 2367` instead of `-r 100000`. No matter if you use Tromp or silentarmy, I just tested both:
```
./genesis.py -c mainnet -t 1525713114 -Z Testfor41b3ad374fe454b5535b8189a6c977176c6640aa2b694b0d16aa852c758a4ad10 -p 04edebd8f71c56038cfa665a8049bfba8a927de78819c8f018b2e7d434f0cbad9c2450eb1d4ef036628e60cf164647f8abd4bfa3f61abec6b852711b22abc1bcf7 -s ../equihash/equi -n 2367       
Solution found!
Header Hash: 0002d1473f0543360bf3b2c05d41c672bd840af9f5c5151438b6350f4df65d7f
Nonce: 0000000000000000000000000000000000000000000000000000000000002367
0015ccf26403b133e9953051c1fa44add652d7760f0542bdf40b87453cbc2dd08e76ebc7e90999e8bcf402ffa9d205e7bdf5d49d017988b255c55a351b2c4d0dd09757005393deae4882bf1951e338e9824ecbd60b274ce517e7b3bbc0d0238c8d2e79494acccc579649ea73e465e2bf0f8cfb8670736ed9c393cb1d43f31b117edd6a774665f0ae920f68d0dcf9c93493aa0d2c3e7da38315aad1f73c749857caa3ef15ae3e71c400a0f26b2258928588c1f220d13b07d48f1e11b66018feff3e3889bc1d9466c48205fe895176d60d79a500b87977fddb21c57e9744decbd61ffd463538efc603a4036e00e2c64f94b0708b94d4aa0d30ae7732b50320216e634671986a35b03f3d37972720081e2f9b322a3bbdc2d3e2ed7e6c26250e3f6157c7675f15a204b82b1a7619f1d705299143c9a3b051970c700e6131e736fcc4679e21f60d43cc56258fcd5be0b6981d033e39164258787319240154301c8432027b50181d0e005a85ac05a93a97db7259ac20f392937fb8f708153618d94019e11792e3f8663bed852337011ec6e2290e1185a2160cdb4469b4f65adeff1d9644ffe8cc0715dde20b23b6b32ecfe0c6fbbb83ddc748dbe25512099ac6bef26e39951f347828b855252dadb5a775255207251c4a7db2e75c62deb1aaa74acd87df34222830ae0d1663582174f5034b33dd2ebfbed3ff1d0f1049e2ad4104b6966bdfd27a066907d9d1bf9b4a58368e2eeb37357065c0c7f3fcc4c4fc79b4e574661f16bc429cdb5fe03587e2f181cbeee61d2779bc0f782d8d576a575ca8392dd833172739a466f3945f0c8414ee5d1afb636f6d73338352951e87f2b0b8dcc78a2494caa874bb9a1ddfa2565ed4facfd3bace7fbc411615c0b9206da1b5c7e984ec2e4b4a0eda2f1c6dc8344d7c25d165b1313d48c7525cceab99feeb9603f10102dd766a98af9be90f2261202cd762c0655b4b0217a60e71de4860459a53251f9f5f66072e901e4beb15eff6afba376a57db5f81ed467e1548d3ab6b5b982491594cd3b619cfff7be3e3acab917bc3ce7ed9fc022e168f6d437efae303e904a4d4d54388f79d64621663c973f08f59fcef4f427b436eedfe1b921373753efa2a04b6aa5b41e8951400e5c0432a44d4d8254f6c4b17bd956fc4439de1f6ca6fceb5fb74751c1b5f02b469c6e66cddcfd3e8f1eee89381b896d45c0f143960e6a0030fa82ca447a70cfe69c9ee3b5cbf6b4e079614a271d58ecf695b408863bb137cda2ddcf27026192d518a898b37667734541cecbf9dfe11f84cf41e123e4c9b4ead7eff6b54e3727d6ffa008393edd02e6e8246780bfc93b2b897191d4432aecd02fc238d38fbfc02d5b025ffe884c3b5c12a22a17bd0dd02324ff40ef40e95437918e9556f782f40e9bb6f3b845a014b8a7e38c8de60b41df0b16bcdb21d5527ebed84176e2d51bd14a5f300be03e130ad90c2e54b5795500bb1119f818de881e1dd93ce8ce1c031bc823215773929e4a5e052ddfbaa691bd564f45e4f9cbdfe33d707b5750202f5a4ffbed2f55f40c1dc523e79fca6b80a19a77772d9bcdd0e376217fa25aada193ed276220e53a7241498584932df8418b45f4d7130c92cbc4b5865d3cb9bdcbd3f39f2f62502c9b409b7cf0e539505bce30d39c850e195cc644370c5103dc2a970840f0ca2d30ed3e24c47a2b750cc9f27b9d04a40453f8e1fd614a6d9f332bfce0437c729ef30a791a0df22bd23cfb6ade20de8ef8b24b7987a564e4aaa50bdc26609949ff768837fb2f03b31f209e474a4a56556697c3beedb4e0dbc3231f22047d0596bf7a2bb179fc4530a4196197c10ba597c805242fc300d913e81972983199beee8f50ceb6ba1a016e913eb1cbf027b1cf874
```

**Comment by miranos** [comment]
Very big thank's sir !

Test for: REGTEST / TESTNET / MAINNET

ALL WORKING WELL !

You are the best !
