### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Sitexpay** [sebastianst/GenesisZ#13]
Please help me!
What command do I need to get such data:
1.main
hashGenesisBlock
hashMerkleRoot
bits
nonce
2.testnet
3.regtest

I tried to introduce an example of your command and got this result
![screen](https://user-images.githubusercontent.com/39833678/41413986-9d360f3a-7006-11e8-9cf9-bae5d6893d35.png)
![screen1](https://user-images.githubusercontent.com/39833678/41414608-58454ca4-7008-11e8-9dcb-d59420b63375.png)

**Comment by sebastianst** [comment]
You got the solution printed. Try adding the `-v` option to see more information like the one you asked about.
