### ISSUE TITLE
issue on generating  hash 

### ISSUE THREAD

**Issue by potadibyo** [sebastianst/GenesisZ#16]
Could Not find binarary /path/to/equihash/equi/; is the path correct ?
Exiting.
MY given commamd is: 
./genesis.py -c mainnet -t 1534505672 -E 0x1d00ffff -C MRC  -z "Vajpayee, Fierce Nehru Critic, Gave Best Speech After His Death: Ex-Aide" -s '/path/to/equihash/equi' -T 4 -n 2083236893

**Comment by sebastianst** [comment]
`/path/to/equihash/equi/` is a placeholder ;) point it to your `equi` executable as described in the README.

**Comment by potadibyo** [comment]
Thanks @sebastianst for your information.......
I do the following steps please checks those containing any wrong steps or not.....
(GenesisZ) root@vmi153581:~/ws/GenPyHasBl/GenesisZ#./genesis.py -c testnet -t 1536059007  -E 0x1f07ffff -C MoonRoomCash -z "Current BTC Block Height. BTC #539914 - 0000000000000000001a10fef98626fdb55cd511fbd453694837f9dea0666a34"  -s '/root/ws/equihash/equi '  -n 2e6 -T 4 -S tromp
still giving error 
Solver stopped before valid solution found.
Exiting.
I acutally try to mine a genesis block for equihash based new crypto currency
Need Your help @sebastianst indeed
Thanks,
Dibyajit
