### ISSUE TITLE
Failed building wheel for pyblake2

### ISSUE THREAD

**Issue by vectorean** [sebastianst/GenesisZ#3]
root@vps:~/GenesisZ# ./genesis.py
Traceback (most recent call last):
  File "./genesis.py", line 18, in <module>
    from bitcoin.core import *
ImportError: No module named 'bitcoin'

root@vps:~/GenesisZ# pip install bitcoin
Requirement already satisfied: bitcoin in /usr/local/lib/python2.7/dist-packages

**Comment by sebastianst** [comment]
Try with python 3, i.e., use `virtualenv3`

**Comment by vectorean** [comment]
Thanks! I used "python3 -m venv GenesisZ" with installing some libs.
