### ISSUE TITLE
Adopt to new bitcoin module API

### ISSUE THREAD

**Issue by vectorean** [sebastianst/GenesisZ#4]
'CEquihashHeader' is not defined in genesis.py on line 151.

**Comment by danis-ahmaev** [comment]
I think that you need to make some changes. Instead of obsoleted 'virtualenv3' we must user 'python3 -m venv' and change name of function SelectCoreParams to '_SelectCoreParams'.

**Comment by danis-ahmaev** [comment]
'x' is not defined

**Comment by sebastianst** [comment]
Please change the title to the main issue. Looks like the bitcoin lib python API has changed quite a bit, so this is the main issue here...
Unfortunately, I don't have time at the moment to investigate all changes that have to be made to make this code function again with the newest bitcoin python module.

**Comment by sebastianst** [comment]
I just did a fresh checkout of GenesisZ and silentarmy and cannot reproduce this error.
```
# pip freeze
certifi==2018.4.16
chardet==3.0.4
idna==2.6
pyblake2==1.1.2
python-bitcoinlib==0.10.1
requests==2.18.4
urllib3==1.22
```
Do you still have this error with a fresh checkout of GenesisZ?
