### ISSUE TITLE
Issue on generating genesis block on regtest

### ISSUE THREAD

**Issue by ghost** [sebastianst/GenesisZ#7]
Hi there,
I need to generate a new genesis block on regtest but I have an issue because silentarmy does not support  "-n 48 -k 5":

GenesisZ]$ ./genesis.py -c regtest -t 1511954736 -Z LitecoinZ6f099db24212fc48cc80bcf8d46874cd44a7a196625cc1e08a567bff77da2e79 -p 04bccfb90b0364ac381985755cb15f2e14214dd9239de85d9ff58bf2eed145dc776daa3469b29b50e459939df5346da0d6d40dbc698830f2022fe64ed6aa701f74 -b 0x207fffff -E 486604799 -v -s "../silentarmy/sa-solver -n 48 -k 5 --use 1 --nonces 4000 -i" 
Chain: regtest
Time: 1511954736
Start Nonce: 0000000000000000000000000000000000000000000000000000000000000000
Pubkey: 04bccfb90b0364ac381985755cb15f2e14214dd9239de85d9ff58bf2eed145dc776daa3469b29b50e459939df5346da0d6d40dbc698830f2022fe64ed6aa701f74
Solver: ['../silentarmy/sa-solver', '-n', '48', '-k', '5', '--use', '1', '--nonces', '4000', '-i']
pszTimestamp: LitecoinZ6f099db24212fc48cc80bcf8d46874cd44a7a196625cc1e08a567bff77da2e79
TX/merkle root hash: f67057581d7f6b4316cd854aac32d14228f9d9ed92125317eeb2efbadc395d01
Starting solver with command ['../silentarmy/sa-solver', '-n', '48', '-k', '5', '--use', '1', '--nonces', '4000', '-i', '040000000000000000000000000000000000000000000000000000000000000000000000015d39dcbaefb2ee17531292edd9f92842d132ac4a85cd16436b7f1d585770f6000000000000000000000000000000000000000000000000000000000000000030991e5affff7f200000000000000000000000000000000000000000000000000000000000000000']
Solver started.
Solver banner:
Unsupported n (must be 200)

Traceback (most recent call last):
  File "./genesis.py", line 232, in <module>
    main()
  File "./genesis.py", line 38, in main
    solution, nonce = loop.run_until_complete(findValidSolution(eh, args.solver))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./genesis.py", line 191, in findValidSolution
    nonce, sols = await parseSolutions(solver)
  File "./genesis.py", line 223, in parseSolutions
    _, nonce, solc, _ = line.split()
ValueError: not enough values to unpack (expected 4, got 0)

How can I do that? There is another solver to use with your tool?

Thanks,
Marco

**Comment by sebastianst** [comment]
I already spend some time on that, to no avail so far. Silent Army still doesn't support parameters `n,k=48,5`, see also this [recent issue of silentarmy](https://github.com/mbevand/silentarmy/issues/108). It is also mentioned in the Readme as an open todo.

**Comment by madtomic** [comment]
@marcofortina @sebastianst 

Hi, any idea how to get the hashMerkleRoot?

**Comment by sebastianst** [comment]
Tromp's solver is now supported. Give it a go, don't forget to `make equi485` and use that binary in `-s`.

**Comment by Moonroom-Cash** [comment]
./genesis.py -c mainnet -t 1512832667  -b 0x1f07ffff -E 486604799  -Z LitecoinZ6f099db24212fc48cc80bcf8d46874cd44a7a196625cc1e08a567bff77da2e79  -p 048c64efd9e320f8dc6ab14f3e2c674877fe1b027f62afaffdd46ee4a191b3be90dd5a3bf8c7f6b2205dbde788793e97a645a16c2d8bede3dca0182dfc3cc15137  -s '/root/ws/equihash/equi'  -n 2e6

that does not shows proper hash 
pszTimestamp found!
pszTimestamp:  LitecoinZ6f099db24212fc48cc80bcf8d46874cd44a7a196625cc1e08a567bff77da2e79
Merkle root found!
TX/merkle root hash: f67057581d7f6b4316cd854aac32d14228f9d9ed92125317eeb2efbadc395d01
script PubKey found!
script PubKey: ac741f70aad64ee62f02f2308869bc0dd4d6a06d34f59d9359e4509bb26934aa6d77dc45d1eef28bf59f5de89d23d94d21142e5fb15c75851938ac64030bb9cfbc0441
Solution found!
Solver stopped before valid solution found.
Exiting.
if i am doing anythings wrongs to produce litecoinz merkle root and genesis hash (i already tested snowgem,zclassic and got proper result , den searching through this igot this code and tested shows error)
Thanks 
Dibyajit

**Comment by sebastianst** [comment]
This has nothing to do with this (already closed) issue, does it?
I don't know LitecoinZ, is `0x2e6` the nonce that produces its genesis block? That's the one you specified with `-n`. Also, you don't specify `-r`, that is, how many nonces upwards from the nonce you specify with `-n` to test. So the solver stops after a single nonce.
General usage questions shouldn't be asked as issues, but posted in a forum, like reddit, bitcointalk or zcash forums. Thanks!
